#- name: set prompt
#  ansible.builtin.shell: set-prompt {{ app_name }}-{{ env }}

- name: Load Maven
  ansible.builtin.include_role:
    name: common
    tasks_from: maven

- name: install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load SQL File
  ansible.builtin.debug: mysql -h mysql-{{ env }}.devops11.online -uroot -pRoboShop@1 < /app/db/{{ item }}.sql
    - schema
    - app-user
    - master-data

- name: restart Shipping
  ansible.builtin.systemd_service:
    name: shipping
    state: restarted
