- name: Install python
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop:
    - python3
    - gcc
    - python3-devel

- name: Load App Prerequisites
  ansible.builtin.include_tasks:
    file: app_pre-requisites.yml

- name: Install python Dependencies
  ansible.builtin.shell: pip3 install -r requirements.txt
  args:
    chdir: /app

- name: systemD setup
  ansible.builtin.include_tasks:
    file: systemd_setup.yml
