- name: Copy the service file
  ansible.builtin.template:  # TEMPLATE IS USED HERE BECAUSE THE ENVIRONMENT VARIABLE GETS REPLACED.
    src: "{{  }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: Start service
  ansible.builtin.systemd_service:
    name: "{{  }}"
    state: restarted
    enabled: yes
    daemon_reload: yes